const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.LOS,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{ArrastrarYSoltar: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{TextoCPU: 0},
	{TextoDisipador: 0},
	{TextoFuenteAlimentacion: 0},
	{TextoRam: 0},
	{TextoGrafica: 0},
	{TextoPlacaBase: 0},
	{CualEsElNombreDeEstosComponentes: 0},
	{LíneaDeVisión: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto7: 0},
	{Texto8: 0},
	{Texto9: 0},
	{Texto10: 0},
	{Texto11: 0},
	{Texto12: 0},
	{Texto13: 0},
	{Sprite14: 0},
	{Sprite15: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	TextoCPU: class extends self.ITextInputInstance {},
	TextoDisipador: class extends self.ITextInputInstance {},
	TextoFuenteAlimentacion: class extends self.ITextInputInstance {},
	TextoRam: class extends self.ITextInputInstance {},
	TextoGrafica: class extends self.ITextInputInstance {},
	TextoPlacaBase: class extends self.ITextInputInstance {},
	CualEsElNombreDeEstosComponentes: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	Texto8: class extends self.ITextInstance {},
	Texto9: class extends self.ITextInstance {},
	Texto10: class extends self.ITextInstance {},
	Texto11: class extends self.ITextInstance {},
	Texto12: class extends self.ITextInstance {},
	Texto13: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {}
}